### ISSUE TITLE
NoSuchMethodError on 2021.1 EAP

### ISSUE THREAD

**Issue by cypressious** [Witik/RiderUserSecrets#13]
JetBrains Rider 2021.1 EAP 2
Build #RD-211.4961.12, built on February 3, 2021
Rider EAP User
Expiration date: March 5, 2021
Runtime version: 11.0.9.1+11-b1257.1 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
.NET Framework 4.0.30319.42000
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, ide.mac.bigsur.alerts.enabled=false, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, ea.enable.developers.list=false, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, ide.new.project.model.cache=false, ide.new.project.model=false, rdclient.asyncActions=false
Non-Bundled Plugins: String Manipulation (8.10.191.000.0), eu.gillissen.rider.usersecrets (1.0.1), com.eny.i18n (2.5.0)

```
java.lang.NoSuchMethodError: 'void com.jetbrains.rider.run.environment.MSBuildEvaluator$PropertyRequest.<init>(java.lang.String, java.lang.String, java.lang.Iterable)'
	at eu.gillissen.rider.usersecrets.OpenUserSecretsAction$actionPerformed$1.run(OpenUserSecretsAction.kt:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:964)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:612)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:167)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by tankbob** [comment]
Yep - Me too, exactly the same error

**Comment by maffelbaffel** [comment]
Same error for me.

**Comment by thulaOskar** [comment]
@Witik It would be nice to get this one in :P #14 
Using this plugin every day.. Keep up the good work :)

**Comment by Eonasdan** [comment]
@thulaOskar what I do in the meantime is open the file in rider and then add to the Favorites

**Comment by thulaOskar** [comment]
> @thulaOskar what I do in the meantime is open the file in rider and then add to the Favorites

@Eonasdan Thanks alot for this tip, this is a great solution! (woking on a microservice solution in a monorepo)
