### ISSUE TITLE
ActionUpdateThread.OLD_EDT is depreciated warning in Rider 2024.1

### ISSUE THREAD

**Issue by madhon** [Witik/RiderUserSecrets#29]
The following error pops up in Rider 2024.1 when this plugin is used.

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'eu.gillissen.rider.usersecrets.InitUserSecretsAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: eu.gillissen.rider.usersecrets]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by dkakaruk-woolworthslimited** [comment]
I hope the author is OK because there's no activity on his github for a quite a while.
