### ISSUE TITLE
Trows Error on MacOS 

### ISSUE THREAD

**Issue by kokaruk** [Witik/RiderUserSecrets#3]
I think something isn't right with the paths:

/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/182.4231.496/Rider 2018.2.app/Contents/bin/~/.microsoft/usersecrets/79a3edd0-2092-40a2-a04d-dcb46d5ca9ed/secrets.json

java.lang.IllegalStateException: PsiDocumentManager return null psi for DocumentImpl[file:///Users/<% *my username here *% >/Library/Application Support/JetBrains/Toolbox/apps/Rider/ch-0/182.4231.496/Rider 2018.2.app/Contents/bin/~/.microsoft/usersecrets/79a3edd0-2092-40a2-a04d-dcb46d5ca9ed/secrets.json]
	at com.jetbrains.rider.daemon.components.RiderMarkupHost$1.invoke(RiderMarkupHost.kt:49)
	at com.jetbrains.rider.daemon.components.RiderMarkupHost$1.invoke(RiderMarkupHost.kt:27)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:138)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:59)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:100)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:59)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:118)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:59)
	at com.jetbrains.rider.util.reactive.Signal.fire(Signal.kt:24)
	at com.jetbrains.rider.util.reactive.ViewableMap.put(ViewableMap.kt:30)
	at com.jetbrains.rider.document.DocumentHost.a(DocumentHost.kt:128)
	at com.jetbrains.rider.document.DocumentHost.access$viewEditableEntity(DocumentHost.kt:36)
	at com.jetbrains.rider.document.DocumentHost$1$2$1.run(DocumentHost.kt:70)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:925)
	at com.jetbrains.rider.document.DocumentHost$1$2.invoke(DocumentHost.kt:67)
	at com.jetbrains.rider.document.DocumentHost$1$2.invoke(DocumentHost.kt:36)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:138)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(ViewableCollections.kt:59)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:100)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(ViewableCollections.kt:59)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:118)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(ViewableCollections.kt:59)
	at com.jetbrains.rider.util.reactive.Signal.fire(Signal.kt:24)
	at com.jetbrains.rider.util.reactive.ViewableMap.put(ViewableMap.kt:30)
	at com.jetbrains.rider.framework.impl.RdMap$put$1.invoke(RdMap.kt:165)
	at com.jetbrains.rider.framework.base.RdReactiveBase.localChange$rd_framework_jvm(RdReactiveBase.kt:43)
	at com.jetbrains.rider.framework.impl.RdMap.put(RdMap.kt:165)
	at com.jetbrains.rider.document.DocumentHost.registerModelDocument$rider(DocumentHost.kt:346)
	at com.jetbrains.rider.editors.TextControlHost.bindEditor(TextControlHost.kt:360)
	at com.jetbrains.rider.editors.TextControlHost.editorCreated(TextControlHost.kt:271)
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy43.editorCreated(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.a(EditorFactoryImpl.java:211)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:163)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.i(TextEditorComponent.java:144)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.<init>(TextEditorComponent.java:81)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:93)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$PsiAwareTextEditorComponent.<init>(PsiAwareTextEditorImpl.java:86)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.createEditorComponent(PsiAwareTextEditorImpl.java:71)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:49)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:44)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditor(PsiAwareTextEditorProvider.java:35)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$9(FileEditorManagerImpl.java:857)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:652)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:665)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:960)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl3(FileEditorManagerImpl.java:782)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$4(FileEditorManagerImpl.java:764)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:139)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:97)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:87)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:73)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:764)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:695)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.openFile(FileEditorManagerEx.java:139)
	at eu.gillissen.rider.usersecrets.OpenUserSecretsAction.actionPerformed(OpenUserSecretsAction.kt:32)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:294)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:114)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:114)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:529)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:49)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:549)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Witik** [comment]
Thanks for the report, I submitted a new version for approval. should arrive within a few days

**Comment by Witik** [comment]
@kokaruk have you had the chance to test the new version?

**Comment by kokaruk** [comment]
Sorry, mate. Was away. Works a treat! Thank you.
